spring:
  datasource:
    url: jdbc:mysql://zaxtyson.cn:3306/now_score?useUnicode=true&characterEncoding=UTF-8
    username: now_score
    password: rcmsKBt5pskyMba3
    driver-class-name: com.mysql.cj.jdbc.Driver
